### ISSUE TITLE
Resize Image or Timestamp?

### ISSUE THREAD

**Issue by mrxinu** [Acidham/alfred-resize-image#1]
I'm very confused - it says resize image but the workflow is for timestamp adjustments that go to the clipboard? 👀

**Comment by Acidham** [comment]
Please explain use case and send me log output from the workflow.

**Comment by mrxinu** [comment]
Can do! Here we go.

1. Google for "alfred workflow resize"
2. Click on the packal.org link that goes here: [https://www.packal.org/workflow/resize-image](https://www.packal.org/workflow/resize-image)
3. Click on the 'View on Github' link that goes here: [https://github.com/Acidham/alfred-resize-image](https://github.com/Acidham/alfred-resize-image)
4. Note that the source code and workflow in this repository are for a timestamp generator and resizing images here: [https://github.com/Acidham/alfred-resize-image/blob/main/src/info.plist#L105-L129](https://github.com/Acidham/alfred-resize-image/blob/main/src/info.plist#L105-L129)
5. Go back to [the packal.org page](https://www.packal.org/workflow/resize-image) and click the 'Download' link on the right which goes here: [https://github.com/packal/repository/raw/master/com.apple.alfred2.workflow.resizeimage/resize_image.alfredworkflow](https://github.com/packal/repository/raw/master/com.apple.alfred2.workflow.resizeimage/resize_image.alfredworkflow)
6. Use the resize image workflow

**Comment by Acidham** [comment]
I'm not sure what happened here but anyhow I committed WF gain
