### ISSUE TITLE
Working on Monterey?

### ISSUE THREAD

**Issue by AnthoPakPak** [Acidham/alfred-resize-image#2]
Hey!
I've used this workflow for a few years. Recently it stopped working. I suspect it's because of Monterey.
I've investigated a bit, and the workflow fails because of AppleScript returning empty dimensions of image. Basically, this line `copy dimensions of this_image to {W, H}` doesn't add any value into dimensions. So it makes the workflow fail.
I suspected an issue with permission or so, but I do have Image Events whitelisted in Privacy & Security Automation settings.
Does it work on your side?
Thanks!

**Comment by Acidham** [comment]
I had the same issue and stopped using the workflow. With Alfred 5, I built a workflow using Automation Tasks, but I didn't publish the workflow so far. Are you interested in the new Workflow? 
Are you on Alfred 5?

**Comment by AnthoPakPak** [comment]
Hey mate, sorry for my late answer.
Glad to know it's not just me. I'm using Alfred 5 so yeah it could be cool if you share the new workflow 👍
Thanks!

**Comment by Acidham** [comment]
https://alfred.app/workflows/acidham/image-shrinker/

**Comment by AnthoPakPak** [comment]
Thanks, working perfectly! ✌️
